[package]
name = "scrabble"
version = "0.1.0"
authors = ["James Baum <jamestease@epichealth.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.102"
serde_cbor = "0.10.2"
